// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// RegistersColumns holds the columns for the "registers" table.
	RegistersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "username", Type: field.TypeString},
		{Name: "password", Type: field.TypeString},
	}
	// RegistersTable holds the schema information for the "registers" table.
	RegistersTable = &schema.Table{
		Name:       "registers",
		Columns:    RegistersColumns,
		PrimaryKey: []*schema.Column{RegistersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		RegistersTable,
	}
)

func init() {
}
