// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"

	"github.com/AnirudhAgnihotri2902/architecture-setup-go/ent/migrate"

	"github.com/AnirudhAgnihotri2902/architecture-setup-go/ent/registers"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Registers is the client for interacting with the Registers builders.
	Registers *RegistersClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	client := &Client{config: cfg}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Registers = NewRegistersClient(c.config)
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:       ctx,
		config:    cfg,
		Registers: NewRegistersClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:       ctx,
		config:    cfg,
		Registers: NewRegistersClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Registers.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Registers.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.Registers.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *RegistersMutation:
		return c.Registers.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// RegistersClient is a client for the Registers schema.
type RegistersClient struct {
	config
}

// NewRegistersClient returns a client for the Registers from the given config.
func NewRegistersClient(c config) *RegistersClient {
	return &RegistersClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `registers.Hooks(f(g(h())))`.
func (c *RegistersClient) Use(hooks ...Hook) {
	c.hooks.Registers = append(c.hooks.Registers, hooks...)
}

// Use adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `registers.Intercept(f(g(h())))`.
func (c *RegistersClient) Intercept(interceptors ...Interceptor) {
	c.inters.Registers = append(c.inters.Registers, interceptors...)
}

// Create returns a builder for creating a Registers entity.
func (c *RegistersClient) Create() *RegistersCreate {
	mutation := newRegistersMutation(c.config, OpCreate)
	return &RegistersCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Registers entities.
func (c *RegistersClient) CreateBulk(builders ...*RegistersCreate) *RegistersCreateBulk {
	return &RegistersCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Registers.
func (c *RegistersClient) Update() *RegistersUpdate {
	mutation := newRegistersMutation(c.config, OpUpdate)
	return &RegistersUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *RegistersClient) UpdateOne(r *Registers) *RegistersUpdateOne {
	mutation := newRegistersMutation(c.config, OpUpdateOne, withRegisters(r))
	return &RegistersUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *RegistersClient) UpdateOneID(id int) *RegistersUpdateOne {
	mutation := newRegistersMutation(c.config, OpUpdateOne, withRegistersID(id))
	return &RegistersUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Registers.
func (c *RegistersClient) Delete() *RegistersDelete {
	mutation := newRegistersMutation(c.config, OpDelete)
	return &RegistersDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *RegistersClient) DeleteOne(r *Registers) *RegistersDeleteOne {
	return c.DeleteOneID(r.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *RegistersClient) DeleteOneID(id int) *RegistersDeleteOne {
	builder := c.Delete().Where(registers.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &RegistersDeleteOne{builder}
}

// Query returns a query builder for Registers.
func (c *RegistersClient) Query() *RegistersQuery {
	return &RegistersQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeRegisters},
		inters: c.Interceptors(),
	}
}

// Get returns a Registers entity by its id.
func (c *RegistersClient) Get(ctx context.Context, id int) (*Registers, error) {
	return c.Query().Where(registers.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *RegistersClient) GetX(ctx context.Context, id int) *Registers {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *RegistersClient) Hooks() []Hook {
	return c.hooks.Registers
}

// Interceptors returns the client interceptors.
func (c *RegistersClient) Interceptors() []Interceptor {
	return c.inters.Registers
}

func (c *RegistersClient) mutate(ctx context.Context, m *RegistersMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&RegistersCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&RegistersUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&RegistersUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&RegistersDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Registers mutation op: %q", m.Op())
	}
}
