// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/AnirudhAgnihotri2902/architecture-setup-go/ent/predicate"
	"github.com/AnirudhAgnihotri2902/architecture-setup-go/ent/registers"
)

// RegistersUpdate is the builder for updating Registers entities.
type RegistersUpdate struct {
	config
	hooks    []Hook
	mutation *RegistersMutation
}

// Where appends a list predicates to the RegistersUpdate builder.
func (ru *RegistersUpdate) Where(ps ...predicate.Registers) *RegistersUpdate {
	ru.mutation.Where(ps...)
	return ru
}

// SetUsername sets the "username" field.
func (ru *RegistersUpdate) SetUsername(s string) *RegistersUpdate {
	ru.mutation.SetUsername(s)
	return ru
}

// SetPassword sets the "password" field.
func (ru *RegistersUpdate) SetPassword(s string) *RegistersUpdate {
	ru.mutation.SetPassword(s)
	return ru
}

// Mutation returns the RegistersMutation object of the builder.
func (ru *RegistersUpdate) Mutation() *RegistersMutation {
	return ru.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ru *RegistersUpdate) Save(ctx context.Context) (int, error) {
	return withHooks[int, RegistersMutation](ctx, ru.sqlSave, ru.mutation, ru.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ru *RegistersUpdate) SaveX(ctx context.Context) int {
	affected, err := ru.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ru *RegistersUpdate) Exec(ctx context.Context) error {
	_, err := ru.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ru *RegistersUpdate) ExecX(ctx context.Context) {
	if err := ru.Exec(ctx); err != nil {
		panic(err)
	}
}

func (ru *RegistersUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   registers.Table,
			Columns: registers.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: registers.FieldID,
			},
		},
	}
	if ps := ru.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ru.mutation.Username(); ok {
		_spec.SetField(registers.FieldUsername, field.TypeString, value)
	}
	if value, ok := ru.mutation.Password(); ok {
		_spec.SetField(registers.FieldPassword, field.TypeString, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ru.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{registers.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	ru.mutation.done = true
	return n, nil
}

// RegistersUpdateOne is the builder for updating a single Registers entity.
type RegistersUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RegistersMutation
}

// SetUsername sets the "username" field.
func (ruo *RegistersUpdateOne) SetUsername(s string) *RegistersUpdateOne {
	ruo.mutation.SetUsername(s)
	return ruo
}

// SetPassword sets the "password" field.
func (ruo *RegistersUpdateOne) SetPassword(s string) *RegistersUpdateOne {
	ruo.mutation.SetPassword(s)
	return ruo
}

// Mutation returns the RegistersMutation object of the builder.
func (ruo *RegistersUpdateOne) Mutation() *RegistersMutation {
	return ruo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ruo *RegistersUpdateOne) Select(field string, fields ...string) *RegistersUpdateOne {
	ruo.fields = append([]string{field}, fields...)
	return ruo
}

// Save executes the query and returns the updated Registers entity.
func (ruo *RegistersUpdateOne) Save(ctx context.Context) (*Registers, error) {
	return withHooks[*Registers, RegistersMutation](ctx, ruo.sqlSave, ruo.mutation, ruo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ruo *RegistersUpdateOne) SaveX(ctx context.Context) *Registers {
	node, err := ruo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ruo *RegistersUpdateOne) Exec(ctx context.Context) error {
	_, err := ruo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ruo *RegistersUpdateOne) ExecX(ctx context.Context) {
	if err := ruo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (ruo *RegistersUpdateOne) sqlSave(ctx context.Context) (_node *Registers, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   registers.Table,
			Columns: registers.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: registers.FieldID,
			},
		},
	}
	id, ok := ruo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Registers.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := ruo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, registers.FieldID)
		for _, f := range fields {
			if !registers.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != registers.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ruo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ruo.mutation.Username(); ok {
		_spec.SetField(registers.FieldUsername, field.TypeString, value)
	}
	if value, ok := ruo.mutation.Password(); ok {
		_spec.SetField(registers.FieldPassword, field.TypeString, value)
	}
	_node = &Registers{config: ruo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ruo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{registers.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	ruo.mutation.done = true
	return _node, nil
}
